#!/usr/bin/env bash
# A bash script that prints information about subdomains of bruceshimwa.tech

get_info() {
    local full_domain="$2.$1"
    local record_info=$(dig +noall +answer ${full_domain} | awk '{print $4, $5}')
    local record_type=$(echo $record_info | awk '{print $1}')
    local record_ip=$(echo $record_info | awk '{print $2}')

    echo "The subdomain $2 is a ${record_type} record and points to ${record_ip}"
}

if [[ -z "$2" ]]; then
    for sub in www lb-01 web-01 web-02; do
        get_info $1 $sub
    done
else
    get_info $1 $2
fi
